# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Parth Shah
tagline:          'Supply Chain Professional'
description:      'MSCM Grad @UW, Seattle'
url:              http://parthshah279.github.io

author:
  name:           'Parth Shah'
  email:          parths279@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

gems: [jekyll-paginate]
since:                  2023
emailme:                mailto:parths279@gmail.com
version:                Jan.29.2024
linkedin_username:      parth-b-shah
share_pdf:              no
share_video:            no
# facebook_username: 
# google_plus_username: 
# twitter_username: 
instagram_username:     parthshah279

collections:
  contact:
    output: true
  resume:
    output: true
  projects:
    output: true
  home:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
